version: "3.8"

services:
  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api-server
    environment:
      - CHOKIDAR_USEPOLLING=true

  api-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
